
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 3;
  public static final int CORCHETE_CERRADO = 36;
  public static final int ELSIF = 17;
  public static final int DIFERENTE = 28;
  public static final int RESTA = 38;
  public static final int DOUBLE = 8;
  public static final int DOS_PUNTOS = 32;
  public static final int LEXEMA_STRING = 48;
  public static final int INT = 5;
  public static final int PRINTLN = 23;
  public static final int ARRAY = 15;
  public static final int PARENTESIS_ABIERTO = 33;
  public static final int FOR = 21;
  public static final int NOT = 10;
  public static final int AND = 11;
  public static final int IGUAL = 29;
  public static final int OR = 12;
  public static final int SUMA = 37;
  public static final int IF = 16;
  public static final int PUNTO_COMA = 31;
  public static final int CORCHETE_ABIERTO = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MODULO = 41;
  public static final int MENOR = 24;
  public static final int TRUEE = 13;
  public static final int IDD = 43;
  public static final int ASIGNACION = 42;
  public static final int BYTE = 4;
  public static final int MAYOR = 25;
  public static final int FALSEE = 14;
  public static final int ELSE = 18;
  public static final int NUMERO_LONG = 47;
  public static final int WHILE = 19;
  public static final int MAYOR_IGUAL = 27;
  public static final int FLOAT = 7;
  public static final int LONG = 6;
  public static final int STRING = 9;
  public static final int PARENTESIS_CERRADO = 34;
  public static final int MENOR_IGUAL = 26;
  public static final int DIVISION = 40;
  public static final int NUMERO_FLOAT = 46;
  public static final int NUMERO_ENTERO = 44;
  public static final int PRINT = 22;
  public static final int DO = 20;
  public static final int NUMERO_DOUBLE = 45;
  public static final int MULTIPLICACION = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "CHAR",
  "BYTE",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "STRING",
  "NOT",
  "AND",
  "OR",
  "TRUEE",
  "FALSEE",
  "ARRAY",
  "IF",
  "ELSIF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "PRINTLN",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "DIFERENTE",
  "IGUAL",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "ASIGNACION",
  "IDD",
  "NUMERO_ENTERO",
  "NUMERO_DOUBLE",
  "NUMERO_FLOAT",
  "NUMERO_LONG",
  "LEXEMA_STRING"
  };
}

